version: "1"
services:
  # 服务名
  mysql:
    image: mysql:8.4.1
    # 容器名 --name mysql
    container_name: mysql
    # 端口 -p
    ports:
      - 3306:3306
    # 环境变量 -e
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: 1210449106
      MYSQL_PASSWORD: 123456
    # 数据卷 -v
    volumes:
      - ./data/mysql:/var/lib/mysql/
    # 总是重启 --restart
    restart: always

  redis:
    image: redis:7.2.5
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    # requirepass 密码
    environment:
      - REDIS_PASSWORD=123456
    command: redis-server --appendonly yes  --protected-mode no

  rabbitmq:
    build: ./rabbitmq
#    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: wry
      RABBITMQ_DEFAULT_USER: 1210449106
      RABBITMQ_DEFAULT_PASS: 123456

  seckill-server:
    # 构建镜像，当前目录找Dockerfile文件 创建镜像
    build: ./seckill-server
#    image: seckill-server

    container_name: seckill-server
    restart: always
    # 依赖，写依赖的服务名
    # 运行时先启动依赖的服务
    depends_on:
      - mysql
      - redis
      - rabbitmq

  seckill-web:
    # 构建镜像，当前目录找Dockerfile文件 创建镜像
    build: ./sekill-web
#    image: seckill-web

    container_name: seckill-web
    ports:
      - 8080:8080
    restart: always
    # 依赖，写依赖的服务名
    # 运行时先启动依赖的服务
    depends_on:
      - redis
      - rabbitmq